/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandMenu: typeof import('./../src/components/TheAside/TheSearch/CommandMenu.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    Home: typeof import('./../src/components/TheAside/TheSearch/Raycast/Home.vue')['default']
    ItemList: typeof import('./../src/components/TheAside/ItemList/ItemList.vue')['default']
    Raycast: typeof import('./../src/components/TheAside/TheSearch/Raycast/Raycast.vue')['default']
    RouteList: typeof import('./../src/components/TheAside/RouteList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAside: typeof import('./../src/components/TheAside/TheAside.vue')['default']
    TheButton: typeof import('./../src/components/TheButton/TheButton.vue')['default']
    TheHead: typeof import('./../src/components/TheHead/TheHead.vue')['default']
    TheIcon: typeof import('./../src/components/TheIcon/TheIcon.vue')['default']
    TheItem: typeof import('./../src/components/TheItem/TheItem.vue')['default']
    TheSearch: typeof import('./../src/components/TheAside/TheSearch/TheSearch.vue')['default']
    TheTitle: typeof import('./../src/components/TheAside/TheTitle/TheTitle.vue')['default']
  }
}
